package petrolpark.mc.destroy.chemistry.legacy;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.Nullable;

import com.google.common.base.MoreObjects;
import com.google.common.collect.ImmutableSet;

import net.createmod.catnip.data.Pair;
import net.minecraft.client.resources.language.I18n;
import net.minecraft.network.chat.Component;
import net.minecraft.world.phys.Vec3;

import petrolpark.mc.destroy.Destroy;
import petrolpark.mc.destroy.chemistry.api.error.ChemistryException;
import petrolpark.mc.destroy.chemistry.api.error.ChemistryException.FormulaException.FormulaModificationException;
import petrolpark.mc.destroy.chemistry.legacy.LegacyMolecularStructure.Topology.SideChainInformation;
import petrolpark.mc.destroy.chemistry.legacy.index.DestroyGroupTypes;
import petrolpark.mc.destroy.chemistry.legacy.index.DestroyMolecules;
import petrolpark.mc.destroy.chemistry.naming.INameableProduct;
import petrolpark.mc.destroy.chemistry.serializer.Branch;
import petrolpark.mc.destroy.client.DestroyLang;
import petrolpark.mc.destroy.core.chemistry.MoleculeRenderer;

/**
 * A Molecule is any species - that could be an actual chemical molecule or an inorganic ion.
 * There are two types of Molecule:
 * <ol>
 * <li>Molecules which have an ID (in the form {@code <namespace>:<name>}), and a defined
 * {@link LegacyMolecularStructure structure} and properties - like {@code DestroyMolecules} example.</li>
 * <li>"Novel" Molecules, which are automatically generated by {@code GenericReaction Generic Reactions}.
 * Instead of an ID, these Molecules are stored and refered to with a
 * <a href="https://github.com/petrolpark/Destroy/wiki/FROWNS">FROWNS</a> code.</li>
 * </ol>
 *
 * <p>An instance of this class does not refer to a singular occurrence of a Molecule in a Mixture.
 * Rather each instance is a different Molecule (for example ethene might be one instance, and methanol another).</p>
 *
 * <p>Molecules should only ever be instantiated with a {@link MoleculeBuilder builder}.</p>
*/
public class LegacySpecies implements INameableProduct {

    // ID

    /** The set of name spaces of all mods which add Molecules.*/
    public static final Set<String> NAMESPACES = new HashSet<>();

    /** The set of name spaces which are reserved for novel Molecules.*/
    public static final Set<String> FORBIDDEN_NAMESPACES = new HashSet<>();

    /** All non-novel Molecules known to Destroy, indexed by their {@link LegacySpecies#getFullID ID}.*/
    public static final Map<String, LegacySpecies> MOLECULES = new HashMap<>();

    /** The name space of the mod by which this Molecule was defined.*/
    public final String nameSpace;

    /** The ID of this Molecule, not including its name space.*/
    private String id;

    // PHYSICAL PROPERTIES

    /** The charge of this Molecule, used to balance salts.*/
    private int charge;

    /** The RAM of this Molecule, in grams per mole.*/
    private float mass;

    /** The density of this Molecule when it is liquid or in solution, in grams per Bucket.*/
    private float density;

    /** The temperature (in kelvins) at which this Molecule forms a gas.*/
    private float boilingPoint;

    /** The polarity of this Molecule, used to determine its solubility with other Molecules.*/
    private float dipoleMoment;

    /** The molar heat capacity in joules per mole-kelvin of this Molecule.*/
    private float molarHeatCapacity;

    /** The latent heat of vaporisation of this Molecule, in joules per mole.*/
    private float latentHeat;

    /** The {@link LegacyMolecularStructure} of this Molecule.*/
    private LegacyMolecularStructure structure;

    // REACTIONS

    /** The {@link LegacySpeciesTag tags} which apply to this Molecule.*/
    private Set<LegacySpeciesTag> tags;

    /** The specific Reactions in which this Molecule is a reactant.*/
    private List<LegacyReaction> reactantReactions;

    /** The specific Reactions in which this Molecule is a product.*/
    private List<LegacyReaction> productReactions;

    // DISPLAY PROPERTIES

    /** The last term in the translation key of this Molecule.*/
    private String translationKey;

    /** The color this Molecule adds to a Mixture.*/
    private int color;

    /** The Renderer for this Molecule.*/
    private MoleculeRenderer renderer;

    private LegacySpecies(String nameSpace) {
        this.nameSpace = nameSpace;
        id = null;
        structure = null;

        tags = new HashSet<>();

        reactantReactions = new ArrayList<>();
        productReactions = new ArrayList<>();
    }

    /**
 * If given a:
 * <ul>
 * <li>Molecule ID (e.g. {@code destroy:ethanol}), gives the Molecule identified by that ID, or {@code null} if it does not exist.</li>
 * <li>FROWNS code (e.g. {@code destroy:linear:OCO}), generates the novel Molecule with that structure.</li>
 * </ul>
 * @param id ID or full FROWNS code.
 * @return A new Molecule instance for novel Molecules; the existing Molecule object for known ones
*/
    @Nullable
    public static LegacySpecies getMolecule(String id) {
        if (id == null || id.isEmpty()) return null;
        String[] idComponents = id.split(":");

        LegacySpecies molecule = MOLECULES.get(id);
        if (molecule != null) return molecule;
        if (idComponents.length == 3) {
            return new MoleculeBuilder("novel")
                .structure(LegacyMolecularStructure.deserialize(id))
                .build();
        } else if (idComponents.length == 2) {
            return MOLECULES.get(id);
        }
        if (!"NO_MOLECULE".equals(id)) Destroy.LOGGER.warn("Could not find Molecule '" + id + "'.");
        return null;
    }

    /**
 * Get the String used for storing this Molecule in NBT.
 * <ul>
 * <li>For known Molecules, this will be of the format {@code <namespace>:<id>}.</li>
 * <li>For novel Molecules, this will be their FROWNS code.</li>
 * </ul>
*/
    public String getFullID() {
        if (id == null) {
            return structure.serialize();
        } else {
            return nameSpace + ":" + id;
        }
    }

    /**
 * Checks all known Molecules for those which have the same structure as this one.
*/
    public LegacySpecies getEquivalent() {
        for (LegacySpecies molecule : MOLECULES.values()) {
            if (Math.abs(getMass() - molecule.getMass()) < 0.001) {
                if (structure.serialize().equals(molecule.structure.serialize())) {
                    return molecule;
                }
            }
        }
        return this;
    }

    public String getFROWNSCode() {
        return structure.serialize();
    }

    /** The charge of this Molecule, used to balance salts.*/
    public int getCharge() {
        return charge;
    }

    /** The RAM of this Molecule, in grams per mole.*/
    public float getMass() {
        return mass;
    }

    /** The density of this Molecule when pure, in grams per Bucket.*/
    public float getDensity() {
        return density;
    }

    /** Get the 'concentration' (molar density) of this Molecule when it is the only Molecule in a solution.*/
    public float getPureConcentration() {
        return getDensity() / getMass();
    }

    /** The temperature (in kelvins) at which this Molecule forms a gas.*/
    public float getBoilingPoint() {
        return boilingPoint;
    }

    /** The polarity of this Molecule, used to determine its solubility with other Molecules.*/
    public float getDipoleMoment() {
        return dipoleMoment;
    }

    /** The energy required to heat one mole of this Molecule by one kelvin.*/
    public float getMolarHeatCapacity() {
        return molarHeatCapacity;
    }

    /** The energy required to change one mole of this Molecule from liquid to gas.*/
    public float getLatentHeat() {
        return latentHeat;
    }

    /** Whether this Molecule is cyclic.*/
    public boolean isCyclic() {
        return structure.isCyclic();
    }

    /** Generates a copy of the structure of this Molecule.*/
    public LegacyMolecularStructure shallowCopyStructure() {
        return structure.shallowCopy();
    }

    /** The Set of every Atom in this Formula.*/
    public Set<LegacyAtom> getAtoms() {
        return structure.getAllAtoms();
    }

    /** Whether this Molecule is tagged as being hypothetical.*/
    public boolean isHypothetical() {
        return tags.contains(DestroyMolecules.Tags.HYPOTHETICAL);
    }

    /** Get all the tags this Molecule has.*/
    public ImmutableSet<LegacySpeciesTag> getTags() {
        return ImmutableSet.copyOf(tags);
    }

    /** Whether this Molecule has the given tag.*/
    public boolean hasTag(LegacySpeciesTag tag) {
        if (tag == null) return false;
        return tags.contains(tag);
    }

    /** Whether this Molecule was generated by a Generic Reaction.*/
    public boolean isNovel() {
        return "novel".equals(this.nameSpace);
    }

    /** Gives all Atoms in this Molecule, and how many of each there are.*/
    public Map<LegacyElement, Integer> getMolecularFormula() {
        Map<LegacyElement, Integer> empiricalFormula = new HashMap<>();
        for (LegacyAtom atom : structure.getAllAtoms()) {
            LegacyElement element = atom.getElement();
            if (empiricalFormula.containsKey(element)) {
                int count = empiricalFormula.get(element);
                empiricalFormula.replace(element, count + 1);
            } else {
                empiricalFormula.put(element, 1);
            }
        }
        return empiricalFormula;
    }

    /**
 * Gives all Atoms in this Molecule, and their quantities, in the format {@code AaBbCc...}.
 * @param subscript If {@code true}, Unicode subscript numbers will be used rather than ASCII numbers
*/
    public String getSerlializedMolecularFormula(boolean subscript) {
        Map<LegacyElement, Integer> formulaMap = getMolecularFormula();
        List<LegacyElement> elements = new ArrayList<>(formulaMap.keySet());
        elements.sort(Comparator.naturalOrder());
        StringBuilder formula = new StringBuilder();
        for (LegacyElement element : elements) {
            int count = formulaMap.get(element);
            String number = count == 1 ? "" : (subscript ? DestroyLang.toSubscript(count) : String.valueOf(count));
            formula.append(element.getSymbol()).append(number);
        }
        return formula.toString();
    }

    /** Gives the FROWNS code of this Molecule.*/
    public String getStructuralFormula() {
        return structure.serialize();
    }

    /**
 * A convenience method for getting the stability of a carbon in this structure.
 * @param carbon Can be any Atom, but the approximation is best for carbon
 * @param isCarbanion Whether this calculation should be inverted
*/
    public Float getCarbocationStability(LegacyAtom carbon, boolean isCarbanion) {
        return structure.getCarbocationStability(carbon, isCarbanion);
    }

    /** Mark this Molecule as being a necessary reactant in the given Reaction.*/
    public void addReactantReaction(LegacyReaction reaction) {
        if (reaction.containsReactant(this)) reactantReactions.add(reaction);
    }

    /** Mark this Molecule as being a product in the given Reaction.*/
    public void addProductReaction(LegacyReaction reaction) {
        if (reaction.containsProduct(this)) productReactions.add(reaction);
    }

    /** Remove the given Reaction from this Molecule's reactant index (datapack reload cleanup).*/
    public void removeReactantReaction(LegacyReaction reaction) {
        reactantReactions.remove(reaction);
    }

    /** Remove the given Reaction from this Molecule's product index (datapack reload cleanup).*/
    public void removeProductReaction(LegacyReaction reaction) {
        productReactions.remove(reaction);
    }

    /** Get the list of Reactions of which this Molecule is a necessary Reactant.*/
    public List<LegacyReaction> getReactantReactions() {
        return this.reactantReactions;
    }

    /** Get the list of Reactions by which this Molecule is made.*/
    public List<LegacyReaction> getProductReactions() {
        return this.productReactions;
    }

    /**
 * Get the display name of this Molecule.
 * @param iupac Whether to use the IUPAC systematic name rather than the common one
*/
    @Override
    public Component getName(boolean iupac) {
        if (isNovel()) return Component.literal(getSerlializedMolecularFormula(true));
        return Component.translatable(getTranslationKey(iupac));
    }

    public String getTranslationKey(boolean iupac) {
        if (isNovel()) return "destroy.chemical.unknown";
        String key = nameSpace + ".chemical." + translationKey;
        String iupacKey = key + ".iupac";
        if (iupac && I18n.exists(iupacKey)) {
            key = iupacKey;
        }
        return key;
    }

    /** The color this Molecule adds to a Mixture.*/
    public int getColor() {
        return color;
    }

    /** Whether this Molecule's color is completely transparent.*/
    public boolean isColorless() {
        return color >> 24 == 0;
    }

    /**
 * Get a String representing the charge of this Molecule.
 * @param alwaysShowNumber If true, a Molecule with charge -1 will return {@code 1-} instead of {@code -}, etc.
*/
    public String getSerializedCharge(boolean alwaysShowNumber) {
        StringBuilder chargeString = new StringBuilder();
        if (charge == 0) return chargeString.toString();
        if (alwaysShowNumber || (charge != 1 && charge != -1)) chargeString.append(Math.abs(charge));
        chargeString.append(charge < 0 ? "-" : "+");
        return chargeString.toString();
    }

    /** Get all the functional Groups contained by this Molecule.*/
    public List<LegacyFunctionalGroup<?>> getFunctionalGroups() {
        return structure.getFunctionalGroups();
    }

    // RENDERING

    /** Get a directed structure of this Molecule for use in rendering.*/
    public Branch getRenderBranch() {
        return structure.getRenderBranch();
    }

    /**
 * Get the list of Atoms (and their locations relative to the starting Atom) of all Atoms
 * in the base Topology of this Molecule.
*/
    public List<Pair<Vec3, LegacyAtom>> getCyclicAtomsForRendering() {
        if (!isCyclic()) return List.of();
        return structure.getCyclicAtomsForRendering();
    }

    /** Get the list of Bonds in the base Topology of this Molecule.*/
    public List<LegacyBond> getCyclicBondsForRendering() {
        if (!isCyclic()) return List.of();
        return structure.getCyclicBondsForRendering();
    }

    /** Get the side-chains off of cyclic Atoms in this Molecule.*/
    public List<Pair<SideChainInformation, Branch>> getSideChainsForRendering() {
        if (!isCyclic()) return List.of();
        return structure.getSideChainsForRendering();
    }

    /** Get the Renderer for this Molecule.*/
    public MoleculeRenderer getRenderer() {
        if (renderer == null) {
            renderer = new MoleculeRenderer(this);
        }
        return renderer;
    }

    /**
 * A class for constructing Molecules. Use {@code build()} to get the Molecule.
*/
    public static class MoleculeBuilder {

        private LegacySpecies molecule;

        private Boolean hasForcedDensity = false;
        private Boolean hasForcedBoilingPoint = false;
        private Boolean hasForcedDipoleMoment = false;
        private Boolean hasForcedMolarHeatCapacity = false;
        private Boolean hasForcedLatentHeat = false;

        private String translationKey;

        /**
 * @param nameSpace The name space for Molecules constructed with this builder
 * @throws IllegalArgumentException If a forbidden name space is used, e.g. {@code novel}.
*/
        public MoleculeBuilder(String nameSpace) {
            molecule = new LegacySpecies(nameSpace);
            if (FORBIDDEN_NAMESPACES.contains(nameSpace)) {
                throw e("Cannot use name space '" + nameSpace + "'.");
            }
            NAMESPACES.add(nameSpace);
            molecule.charge = 0;
            molecule.density = 1000;
        }

        /**
 * The internal ID for this Molecule. Must be unique.
 * If a Molecule is declared without an ID it will not be added to the Molecule register.
*/
        public MoleculeBuilder id(String id) {
            molecule.id = id;
            translationKey(id);
            return this;
        }

        /** Set the structure of this Molecule.*/
        public MoleculeBuilder structure(LegacyMolecularStructure structure) {
            try {
                molecule.structure = structure;
                return this;
            } catch (FormulaModificationException e) {
                throw e("Cannot use structure.", e);
            }
        }

        /** Set the density of this Molecule in grams per Bucket.*/
        public MoleculeBuilder density(float density) {
            molecule.density = density;
            hasForcedDensity = true;
            return this;
        }

        /** Set the boiling point in degrees Celsius.*/
        public MoleculeBuilder boilingPoint(float boilingPoint) {
            return boilingPointInKelvins(boilingPoint + 273);
        }

        /** Set the boiling point in kelvins.*/
        public MoleculeBuilder boilingPointInKelvins(float boilingPoint) {
            molecule.boilingPoint = boilingPoint;
            hasForcedBoilingPoint = true;
            return this;
        }

        /** Set the dipole moment of this Molecule.*/
        public MoleculeBuilder dipoleMoment(int dipoleMoment) {
            molecule.dipoleMoment = dipoleMoment;
            hasForcedDipoleMoment = true;
            return this;
        }

        /** Set the specific heat capacity of this Molecule, in joules per kilogram-kelvin.*/
        public MoleculeBuilder specificHeatCapacity(float specificHeatCapacity) {
            return molarHeatCapacity(specificHeatCapacity / calculateMass());
        }

        /** Set the molar heat capacity for this Molecule, in joules per mole-kelvin.*/
        public MoleculeBuilder molarHeatCapacity(float molarHeatCapacity) {
            if (molarHeatCapacity <= 0f) throw e("Molar heat capacity must be greater than 0.");
            molecule.molarHeatCapacity = molarHeatCapacity;
            hasForcedMolarHeatCapacity = true;
            return this;
        }

        /** Set the latent heat of fusion of this Molecule, in joules per mole.*/
        public MoleculeBuilder latentHeat(float latentHeat) {
            if (latentHeat <= 0f) throw e("Latent heat of fusion must be greater than 0.");
            molecule.latentHeat = latentHeat;
            hasForcedLatentHeat = true;
            return this;
        }

        /** Sets the translation key of this Molecule.*/
        public MoleculeBuilder translationKey(String translationKey) {
            this.translationKey = translationKey;
            return this;
        }

        /** Set the color of this Molecule.*/
        public MoleculeBuilder color(int color) {
            molecule.color = color;
            return this;
        }

        /** Mark this Molecule as being hypothetical.*/
        public MoleculeBuilder hypothetical() {
            return tag(DestroyMolecules.Tags.HYPOTHETICAL);
        }

        /** Adds the given tags to this Molecule.*/
        public MoleculeBuilder tag(LegacySpeciesTag... tags) {
            for (LegacySpeciesTag tag : tags) LegacySpeciesTag.registerMoleculeToTag(molecule, tag);
            molecule.tags.addAll(List.of(tags));
            return this;
        }

        /**
 * Builds the Molecule. This will also:
 * <ul>
 * <li>Estimate the boiling point and dipole moment if they were not supplied.</li>
 * <li>Check existing Molecules to see if a Molecule with the same structure already exists.</li>
 * <li>Use all known functional Group Finders to identify functional Groups in the Molecule.</li>
 * </ul>
*/
        public LegacySpecies build() {

            molecule.mass = calculateMass();
            molecule.translationKey = translationKey;

            if (molecule.structure == null) {
                throw e("Molecule's structure has not been declared.");
            }

            if (molecule.getAtoms().size() >= 100) throw e("Molecule has too many Atoms");

            if ("novel".equals(molecule.nameSpace)) {
                LegacySpecies equivalentMolecule = molecule.getEquivalent();
                if (equivalentMolecule != molecule) {
                    return equivalentMolecule;
                }
            }

            double charge = 0d;
            for (LegacyAtom atom : molecule.getAtoms()) charge += atom.formalCharge;
            molecule.charge = (int) charge;

            if (molecule.getMolecularFormula().containsKey(LegacyElement.R_GROUP)) tag(DestroyMolecules.Tags.HYPOTHETICAL);

            if (!hasForcedDensity && molecule.charge != 0) molecule.density = estimateDensity(molecule);

            if (!hasForcedBoilingPoint && molecule.charge == 0) molecule.boilingPoint = estimateBoilingPoint(molecule);

            if (molecule.charge != 0) {
                boilingPointInKelvins(Float.MAX_VALUE);
            }

            if (!hasForcedDipoleMoment) molecule.dipoleMoment = estimateDipoleMoment(molecule);

            if (!hasForcedMolarHeatCapacity) molecule.molarHeatCapacity = 100f;

            if (!hasForcedLatentHeat) molecule.latentHeat = 20000f;

            if (molecule.color == 0) molecule.color = 0x20FFFFFF;

            molecule.refreshFunctionalGroups();
            molecule.structure.updateSideChainStructures();

            if (!"novel".equals(molecule.nameSpace)) {
                if (molecule.id == null) {
                    throw e("Molecule's ID has not been declared.");
                } else {
                    MOLECULES.put(molecule.nameSpace + ":" + molecule.id, molecule);
                }
            }

            return molecule;
        }

        private float calculateMass() {
            float total = 0f;
            Set<LegacyAtom> atoms = molecule.structure.getAllAtoms();
            for (LegacyAtom atom : atoms) {
                total += atom.getElement().getMass();
            }
            return total;
        }

        /** Very loosely estimate the density of an organic molecule.*/
        private static float estimateDensity(LegacySpecies molecule) {
            return 1000f;
        }

        /** Very loosely estimate the boiling point of an organic molecule.*/
        private static float estimateBoilingPoint(LegacySpecies molecule) {
            int hydrogenBondingGroups = 0;
            int carbonyls = 0;
            int halogens = 0;
            int nitriles = 0;
            for (LegacyFunctionalGroup<?> group : molecule.getFunctionalGroups()) {
                LegacyFunctionalGroupType<?> type = group.getType();
                if (type == DestroyGroupTypes.ALCOHOL
                    || type == DestroyGroupTypes.NON_TERTIARY_AMINE
                    || type == DestroyGroupTypes.CARBOXYLIC_ACID
                    || type == DestroyGroupTypes.UNSUBSTITUTED_AMIDE) hydrogenBondingGroups++;
                if (type == DestroyGroupTypes.CARBONYL
                    || type == DestroyGroupTypes.CARBOXYLIC_ACID
                    || type == DestroyGroupTypes.UNSUBSTITUTED_AMIDE) carbonyls++;
                if (type == DestroyGroupTypes.HALIDE) halogens++;
                if (type == DestroyGroupTypes.NITRILE) nitriles++;
            }
            return 2.04259892128141f * molecule.getMass()
                + 34.3262117819044f * hydrogenBondingGroups
                + 13.0899856936379f * carbonyls
                - 44.7792748741156f * halogens
                + 63.981050928271f * nitriles
                + 178.176866128713f;
        }

        /** Very loosely estimate the dipole moment of a molecule.*/
        private static int estimateDipoleMoment(LegacySpecies molecule) {
            return 0;
        }

        public class MoleculeConstructionException extends ChemistryException {

            private MoleculeConstructionException(String message) {
                super(message);
            }

            private MoleculeConstructionException(String message, Throwable e) {
                super(message, e);
            }
        }

        private MoleculeConstructionException e(String message) {
            return new MoleculeConstructionException(addInfoToMessage(message));
        }

        private MoleculeConstructionException e(String message, Throwable e) {
            return new MoleculeConstructionException(addInfoToMessage(message), e);
        }

        private String addInfoToMessage(String message) {
            String id = molecule.id == null ? "Unknown ID" : molecule.nameSpace + ":" + molecule.id;
            return "Problem building Molecule (" + id + "): " + message;
        }
    }

    private void refreshFunctionalGroups() {
        structure.refreshFunctionalGroups();
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).add("ID", getFullID()).toString();
    }
}
